name: uni_links_desktop
description: A desktop (supports macOS and Windows) implementation of uni_links plugin.
version: 0.1.3
homepage: https://github.com/leanflutter/uni_links_desktop

platforms:
  macos:
  windows:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  uni_links_platform_interface: ^1.0.0
  win32_registry: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    implements: uni_links
    platforms:
      macos:
        pluginClass: UniLinksDesktopPlugin
      windows:
        pluginClass: UniLinksDesktopPlugin
