name: uni_links_desktop
description: A desktop (supports macOS and Windows) implementation of uni_links plugin.
version: 0.1.1
homepage: https://github.com/leanflutter/uni_links_desktop

platforms:
  macos:
  windows:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

  protocol_handler: ^0.1.1
  uni_links_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    implements: uni_links
    platforms:
      macos:
        dartPluginClass: UniLinksDesktop
      windows:
        dartPluginClass: UniLinksDesktop
